/**
 * Collaboration & Social Features - Phase 16 Index
 * DIX VISION v42.2 - Phase 16: Collaboration & Social Features (Weeks 51-54)
 */

export { communitySharingSystem } from './community/CommunitySharing';
export type {
  StrategyPublication,
  StrategyMetrics,
  StrategyReview,
  CommunityLeaderboard,
  LeaderboardMetrics,
  LeaderboardEntry,
  CommunityForum,
  ForumRule,
  ForumThread,
  ForumReply,
  StrategyFollowing,
  CopySettings,
  TimeFilter,
  TradingHours,
  FollowingPerformance,
  CollaborativeResearch,
  Collaborator,
  ResearchData,
  ChartData,
  ResearchConclusion,
  ResearchPublication,
  KnowledgeBase,
  KnowledgeArticle,
  KnowledgeCategory,
  AssetClassCommunity,
  CommunityFeature,
  CommunityResource,
  Contributor,
  CommunitySharingSystem,
  CommunityConfig
} from './community/CommunitySharing';

export { teamCollaborationSystem } from './team/TeamCollaboration';
export type {
  TeamWorkspace,
  TeamMember,
  TeamRole,
  SharedWatchlist,
  WatchlistSymbol,
  SymbolAlert,
  AlertCondition,
  ShareSettings,
  CollaborativeChart,
  ChartIndicator,
  ChartAnnotation,
  ChartDrawing,
  DrawingCoordinate,
  DrawingProperties,
  TeamPortfolio,
  PortfolioAllocation,
  PortfolioPosition,
  PortfolioPerformance,
  PortfolioRiskMetrics,
  TeamAlert,
  TeamSettings,
  TradingHours as TeamTradingHours,
  RiskLimits,
  NotificationSettings,
  TeamAnalytics,
  MemberAnalytics,
  PortfolioAnalytics,
  AssetPerformance,
  WatchlistAnalytics,
  TradingAnalytics,
  CollaborationMetrics,
  TeamAuditLog,
  TeamCollaborationSystem,
  TeamCollaborationConfig
} from './team/TeamCollaboration';

export { educationPlatform } from './education/EducationPlatform';
export type {
  Course,
  CourseCategory,
  CourseLesson,
  LessonType,
  LessonContent,
  LessonResource,
  LessonQuiz,
  QuizQuestion,
  CourseEnrollment,
  CourseProgress,
  QuizAttempt,
  QuizAnswer,
  CourseCertificate,
  Tutorial,
  TutorialCategory,
  TutorialStep,
  StrategyDocumentation,
  DocumentationTemplate,
  TemplateSection,
  DocumentationContent,
  BacktestResults,
  PerformanceMetrics,
  CodeExample,
  FAQ,
  VideoContent,
  VideoCategory,
  VideoComment,
  MentorshipProgram,
  MentorshipCategory,
  MentorshipSession,
  MentorshipEnrollment,
  MentorshipNote,
  MentorshipFeedback,
  LearningTrack,
  TrackBadge,
  UserLearningProfile,
  SkillLevel,
  EducationPlatform,
  EducationConfig
} from './education/EducationPlatform';