"""
Core Contracts Module
Real implementations for DIX VISION contracts
NO PLACEHOLDER - Contract-compliant real implementations
"""

from .api import (
    CredentialItem,
    CredentialsStatusResponse,
    CredentialsSummary,
    PresenceState,
    PresenceStateApi,
    get_presence_state_api,
)
from .development_mode import (
    DevelopmentMode,
    DevelopmentModePolicy,
    get_development_mode_policy,
    set_development_mode,
)
from .engine import (
    EngineCapabilities,
    EngineConfig,
    EngineHealth,
    EngineKind,
    EngineStatus,
    EngineTier,
    HealthState,
    OfflineEngine,
    Plugin,
    PluginLifecycle,
    RuntimeEngine,
)
from .event_provenance import (
    AuthorizationLevel,
    Provenance,
    SourceKind,
    get_authorization_level,
    is_operator_authorized_source,
    verify_provenance,
)
from .events import (
    Event,
    EventKind,
    ExecutionEvent,
    ExecutionStatus,
    HazardEvent,
    HazardSeverity,
    Side,
    SignalEvent,
    SystemEvent,
    SystemEventKind,
)
from .external_signal_trust import ExternalSignalTrustRegistry, load_external_signal_trust
from .governance import (
    ComplianceReport,
    Constraint,
    ConstraintKind,
    ConstraintScope,
    DecisionKind,
    GovernanceDecision,
    GovernanceKind,
    IntentHorizon,
    IntentObjective,
    IntentRiskMode,
    IntentTransitionDecision,
    IntentTransitionRequest,
    LedgerEntry,
    ModeTransitionDecision,
    ModeTransitionRequest,
    OperatorAction,
    OperatorRequest,
    RiskAssessment,
    SystemMode,
)
from .invariants import (
    DIX_01,
    DIX_02,
    DIX_03,
    DIX_04,
    DIX_05,
    DIX_06,
    DIX_07,
    DIX_08,
    DIX_09,
    DIX_10,
    DIX_11,
    DIX_12,
    DIX_13,
    DIX_14,
    DIX_15,
    DIX_16,
    DIX_17,
    DIX_18,
    DIX_19,
    DIX_20,
    InvariantDefinition,
    InvariantID,
    InvariantKind,
    InvariantManager,
    InvariantSeverity,
    InvariantStatus,
    InvariantViolation,
    create_violation,
    get_invariant_manager,
)
from .learning import PatchProposal, StrategyStats
from .learning_evolution_freeze import LearningEvolutionFreezePolicy
from .market import MarketTick
from .mode_effects import (
    EffectKind,
    EffectSeverity,
    ModeEffect,
    ModeEffectManager,
    apply_effect,
    effect_for,
    get_effect_manager,
    get_effects_for_mode,
    revoke_effect,
)
from .operator_consent import (
    ConsentDecision,
    ConsentKind,
    ConsentRequest,
    ConsentStatus,
    OperatorConsent,
    OperatorConsentValidator,
    create_consent_request,
    create_validator,
    edge_requires_consent,
)
from .risk import RiskSnapshot
from .signal_trust import (
    SignalTrust,
    TrustLevel,
    default_cap_for,
    default_signal_trust,
    verify_signal,
)
from .source_trust_promotions import SourceTrustPromotionStore
from .strategy_registry import (
    StrategyKind,
    StrategyLifecycle,
    StrategyLifecycleError,
    StrategyRecord,
    StrategyRegistry,
    StrategyStatus,
    get_strategy_registry,
    is_legal_transition,
)

__all__ = [
    # Events
    "EventKind",
    "HazardSeverity",
    "ExecutionStatus",
    "SystemEventKind",
    "Side",
    "Event",
    "HazardEvent",
    "SignalEvent",
    "SystemEvent",
    "ExecutionEvent",
    # API
    "PresenceState",
    "CredentialItem",
    "CredentialsStatusResponse",
    "CredentialsSummary",
    "PresenceStateApi",
    "get_presence_state_api",
    # Development Mode
    "DevelopmentMode",
    "DevelopmentModePolicy",
    "get_development_mode_policy",
    "set_development_mode",
    # Learning
    "PatchProposal",
    "StrategyStats",
    # Learning Evolution Freeze
    "LearningEvolutionFreezePolicy",
    # External Signal Trust
    "ExternalSignalTrustRegistry",
    "load_external_signal_trust",
    # Source Trust Promotions
    "SourceTrustPromotionStore",
    # Market and Risk
    "MarketTick",
    "RiskSnapshot",
    # Governance
    "GovernanceKind",
    "SystemMode",
    "GovernanceDecision",
    "DecisionKind",
    "IntentHorizon",
    "IntentObjective",
    "IntentRiskMode",
    "RiskAssessment",
    "ConstraintKind",
    "ConstraintScope",
    "OperatorAction",
    "LedgerEntry",
    "OperatorRequest",
    "Constraint",
    "ModeTransitionRequest",
    "ComplianceReport",
    "ModeTransitionDecision",
    "IntentTransitionRequest",
    "IntentTransitionDecision",
    # Engine
    "EngineKind",
    "EngineTier",
    "EngineStatus",
    "HealthState",
    "PluginLifecycle",
    "EngineHealth",
    "EngineConfig",
    "EngineCapabilities",
    "Plugin",
    "RuntimeEngine",
    "OfflineEngine",
    # Event Provenance
    "SourceKind",
    "Provenance",
    "AuthorizationLevel",
    "get_authorization_level",
    "is_operator_authorized_source",
    "verify_provenance",
    # Signal Trust
    "TrustLevel",
    "SignalTrust",
    "default_cap_for",
    "default_signal_trust",
    "verify_signal",
    # Operator Consent
    "ConsentStatus",
    "ConsentKind",
    "ConsentRequest",
    "OperatorConsent",
    "ConsentDecision",
    "OperatorConsentValidator",
    "create_consent_request",
    "create_validator",
    "edge_requires_consent",
    # Strategy Registry
    "StrategyKind",
    "StrategyStatus",
    "StrategyLifecycle",
    "StrategyLifecycleError",
    "StrategyRecord",
    "StrategyRegistry",
    "get_strategy_registry",
    "is_legal_transition",
    # Mode Effects
    "EffectKind",
    "EffectSeverity",
    "ModeEffect",
    "effect_for",
    "get_effects_for_mode",
    "apply_effect",
    "revoke_effect",
    "ModeEffectManager",
    "get_effect_manager",
    # Invariants
    "InvariantKind",
    "InvariantSeverity",
    "InvariantStatus",
    "InvariantID",
    "DIX_01",
    "DIX_02",
    "DIX_03",
    "DIX_04",
    "DIX_05",
    "DIX_06",
    "DIX_07",
    "DIX_08",
    "DIX_09",
    "DIX_10",
    "DIX_11",
    "DIX_12",
    "DIX_13",
    "DIX_14",
    "DIX_15",
    "DIX_16",
    "DIX_17",
    "DIX_18",
    "DIX_19",
    "DIX_20",
    "InvariantDefinition",
    "InvariantViolation",
    "InvariantManager",
    "get_invariant_manager",
    "create_violation",
]
