"""Autonomous Engineering Module."""

from .intelligent_modification import (
    AutomatedTestGenerator,
    CodeContext,
    DependencySafetyChecker,
    IntelligentCodeModifier,
    ModificationObjective,
    ModificationProposal,
    ModificationResult,
    ModificationRisk,
    SafetyConstraintChecker,
    SyntaxSafetyChecker,
    get_intelligent_code_modifier,
)
from .self_healing import (
    AdvancedAnomalyDetector,
    Anomaly,
    AnomalySeverity,
    HealingResult,
    HealingStatus,
    ImpactAssessment,
    ImpactAssessor,
    Resolution,
    ResolutionGenerator,
    RollbackManager,
    RootCause,
    RootCauseAnalyzer,
    SelfHealingSystem,
    get_self_healing_system,
)

__all__ = [
    "ModificationRisk",
    "CodeContext",
    "ModificationObjective",
    "ModificationProposal",
    "ModificationResult",
    "SafetyConstraintChecker",
    "DependencySafetyChecker",
    "SyntaxSafetyChecker",
    "AutomatedTestGenerator",
    "IntelligentCodeModifier",
    "get_intelligent_code_modifier",
    "AnomalySeverity",
    "HealingStatus",
    "Anomaly",
    "RootCause",
    "ImpactAssessment",
    "Resolution",
    "HealingResult",
    "AdvancedAnomalyDetector",
    "RootCauseAnalyzer",
    "ImpactAssessor",
    "ResolutionGenerator",
    "RollbackManager",
    "SelfHealingSystem",
    "get_self_healing_system",
]
